version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28

    steps:
    - checkout
    - restore_cache:
        keys:
        - dep-{{ checksum "./guardian/build.gradle" }}-{{ checksum "./app/build.gradle" }}
        - dep-
    - run: ./gradlew clean test jacocoTestReport --continue --console=plain --max-workers 4
    - save_cache:
        key: dep-{{ checksum "./guardian/build.gradle" }}-{{ checksum "./app/build.gradle" }}
        paths:
          - ~/.gradle
          - ~/.android
          - /usr/local/android-sdk-linux/extras
    - run:
          name: Upload Coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1